package pylint

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestWriteConfigFile(t *testing.T) {
	tmpDir, err := os.MkdirTemp("", "pylint-config-test-*")
	if err != nil {
		t.Fatalf("Failed to create temp dir: %v", err)
	}
	defer func() { _ = os.RemoveAll(tmpDir) }()

	a := NewAdapter(tmpDir)
	config := []byte(`[MASTER]
# Generated by Symphony CLI

[MESSAGES CONTROL]
enable=missing-function-docstring,line-too-long

[FORMAT]
max-line-length=100
`)

	configPath, err := a.writeConfigFile(config)
	if err != nil {
		t.Fatalf("writeConfigFile() error = %v", err)
	}
	defer func() { _ = os.Remove(configPath) }()

	// Verify file exists
	if _, err := os.Stat(configPath); os.IsNotExist(err) {
		t.Error("Config file was not created")
	}

	// Verify content
	content, err := os.ReadFile(configPath)
	if err != nil {
		t.Fatalf("Failed to read config file: %v", err)
	}

	if !strings.Contains(string(content), "[MESSAGES CONTROL]") {
		t.Error("Config file missing [MESSAGES CONTROL] section")
	}

	if !strings.Contains(string(content), "max-line-length=100") {
		t.Error("Config file missing max-line-length option")
	}
}

func TestWriteConfigFile_CreatesDirectory(t *testing.T) {
	tmpDir, err := os.MkdirTemp("", "pylint-config-test-*")
	if err != nil {
		t.Fatalf("Failed to create temp dir: %v", err)
	}
	defer func() { _ = os.RemoveAll(tmpDir) }()

	a := NewAdapter(tmpDir)
	config := []byte(`[MASTER]`)

	configPath, err := a.writeConfigFile(config)
	if err != nil {
		t.Fatalf("writeConfigFile() error = %v", err)
	}
	defer func() { _ = os.Remove(configPath) }()

	// Verify .tmp directory was created
	tmpConfigDir := filepath.Join(tmpDir, ".tmp")
	if _, err := os.Stat(tmpConfigDir); os.IsNotExist(err) {
		t.Error(".tmp directory was not created")
	}
}

func TestGetExecutionArgs(t *testing.T) {
	a := NewAdapter("/test/tools")
	configPath := "/tmp/pylintrc-123"
	files := []string{"src/main.py", "src/utils.py"}

	args := a.getExecutionArgs(configPath, files)

	// Check required arguments
	expectedArgs := []string{
		"--output-format=json",
		"--rcfile=" + configPath,
		"src/main.py",
		"src/utils.py",
	}

	for _, expected := range expectedArgs {
		found := false
		for _, arg := range args {
			if arg == expected {
				found = true
				break
			}
		}
		if !found {
			t.Errorf("getExecutionArgs() missing expected arg: %s", expected)
		}
	}
}

func TestExecute_TempFileCleanup(t *testing.T) {
	tmpDir, err := os.MkdirTemp("", "pylint-exec-test-*")
	if err != nil {
		t.Fatalf("Failed to create temp dir: %v", err)
	}
	defer func() { _ = os.RemoveAll(tmpDir) }()

	a := NewAdapter(tmpDir)
	config := []byte(`[MASTER]`)

	// Write config file
	configPath, err := a.writeConfigFile(config)
	if err != nil {
		t.Fatalf("writeConfigFile() error = %v", err)
	}

	// File should exist
	if _, err := os.Stat(configPath); os.IsNotExist(err) {
		t.Error("Config file should exist after writeConfigFile")
	}

	// Manually remove (simulating cleanup in execute)
	_ = os.Remove(configPath)

	// File should be gone
	if _, err := os.Stat(configPath); !os.IsNotExist(err) {
		t.Error("Config file should be removed after cleanup")
	}
}
