run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - testdata
    - bin

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive
    - unconvert
    - unparam
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - exportloopref
    - nilerr

linters-settings:
  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/DevSymphony/sym-cli

  govet:
    check-shadowing: true
    enable-all: true

  revive:
    rules:
      - name: exported
        disabled: false

  gocyclo:
    min-complexity: 15

  goconst:
    min-len: 3
    min-occurrences: 3

  misspell:
    locale: US

  gosec:
    excludes:
      - G104 # Audit errors not checked

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - gosec
        - goconst

  max-issues-per-linter: 0
  max-same-issues: 0

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
